### ISSUE TITLE
正确的使用方式是重新动态分配一个 `int` 及控制块？

### ISSUE THREAD

**Issue by frederick-vs-ja** [Mq-b/ModernCpp-ConcurrentProgramming-Tutorial#18]
https://github.com/Mq-b/ModernCpp-ConcurrentProgramming-Tutorial/blob/31712e4ef9582548bc047d99af5b5040df9cb385/md/05%E5%86%85%E5%AD%98%E6%A8%A1%E5%9E%8B%E4%B8%8E%E5%8E%9F%E5%AD%90%E6%93%8D%E4%BD%9C.md?plain=1#L525-L543

这两种写法目的明显不同。
- 如果我们在此追求 `shared_ptr` 所管理的对象不可变，那么后面的写法是合理的，虽然可能用 `shared_ptr<const int>` 表示更好。
- 如果我们就是要修改原先创建的 `int` 对象的值，则可能应该考虑使用 [`std::atomic_ref`](https://zh.cppreference.com/w/cpp/atomic/atomic_ref)。

目前教程也缺少 `std::atomic_ref` 的介绍。

**Comment by Mq-b** [comment]
> 这两种写法目的明显不同

我写的时候也感觉的确有点，其实前者目的明显只是修改 shared_ptr 指向的对象，后者是直接替换了 shared_ptr，虽然说的确可行，但是这是个问题。

> 如果我们就是要修改原先创建的 int 对象的值，则可能应该考虑使用 [std::atomic_ref](https://zh.cppreference.com/w/cpp/atomic/atomic_ref)。

这应该是此处想要做的，单纯待修改罢了，而非替换 atomic<shared_ptr> 保有的 shared_ptr

> 目前教程也缺少 std::atomic_ref 的介绍。

的确，没打算详细展开，此处可以后面研究一下。

**Comment by Mq-b** [comment]
或可直接改为：

>正确的用法如下：
>
>```cpp
>std::atomic<std::shared_ptr<int>> ptr = std::make_shared<int>(10);
>std::atomic_ref<int> ref{ *ptr.load() };
>ref = 100; // 原子地赋 100 给被引用的对象
>```
>
>通过使用 [`std::atomic_ref`](https://zh.cppreference.com/w/cpp/atomic/atomic_ref) 我们得以确保在修改共享资源时保持操作的原子性，从而避免了数据竞争。
