### ISSUE TITLE
【可能是笔误】std::defer_lock 的含义

### ISSUE THREAD

**Issue by shaojunjie0912** [Mq-b/ModernCpp-ConcurrentProgramming-Tutorial#8]
这句话[std::defer_lock 的含义](https://mq-b.github.io/ModernCpp-ConcurrentProgramming-Tutorial/md/03%E5%85%B1%E4%BA%AB%E6%95%B0%E6%8D%AE.html#std-unique-lock-%E7%81%B5%E6%B4%BB%E7%9A%84%E9%94%81:~:text=%E9%A6%96%E5%85%88%EF%BC%8C%E6%88%91%E4%BB%AC%E8%A6%81%E4%BA%86%E8%A7%A3%20std%3A%3Adefer_lock%20%E6%98%AF%E2%80%9C%E5%81%87%E8%AE%BE%E8%B0%83%E7%94%A8%E6%96%B9%E7%BA%BF%E7%A8%8B%E5%B7%B2%E6%8B%A5%E6%9C%89%E4%BA%92%E6%96%A5%E4%BD%93%E7%9A%84%E6%89%80%E6%9C%89%E6%9D%83%E2%80%9D%E3%80%82)与[cppref 中](https://zh.cppreference.com/w/cpp/thread/lock_tag#:~:text=defer_lock_t-,%E4%B8%8D%E8%8E%B7%E5%BE%97%E4%BA%92%E6%96%A5%E4%BD%93%E7%9A%84%E6%89%80%E6%9C%89%E6%9D%83,-try_to_lock_t)的不一致。是笔误么？

**Comment by Mq-b** [comment]
是。
